In [1]:
import pandas as pd
import numpy as np

In [2]:
datasets_df = pd.read_csv('/Users/benjaminzelaya/Desktop/ML_Proyecto_Individual_Henry/DEF API/movies_data_final.csv')
crew_df = pd.read_csv('/Users/benjaminzelaya/Desktop/ML_Proyecto_Individual_Henry/DEF API/crew.csv')
cast_df = pd.read_csv('/Users/benjaminzelaya/Desktop/ML_Proyecto_Individual_Henry/DEF API/cast.csv')
movie_genres_df = pd.read_csv('/Users/benjaminzelaya/Desktop/ML_Proyecto_Individual_Henry/DEF API/genres_groupby.csv')
ML_data = pd.read_csv('/Users/benjaminzelaya/Desktop/ML_Proyecto_Individual_Henry/DEF API/ML_data.csv')

In [3]:
datasets_df.columns

Index(['id', 'original_language', 'overview', 'popularity', 'release_date',
       'runtime', 'status', 'tagline', 'title', 'vote_average', 'vote_count',
       'id_bellongs_to_collection', 'name_bellongs_to_collection',
       'poster_bellongs_to_collection', 'backdrop_bellongs_to_collection',
       'Cod_languages', 'name_languages', 'name_genres', 'id_genres',
       'name_companies', 'id_companies', 'Cod_countries', 'country_name',
       'budget', 'revenue', 'release_year', 'return'],
      dtype='object')

In [4]:
crew_df.columns

Index(['id', 'crew_credit_id', 'crew_department', 'crew_gender', 'crew_id',
       'crew_job', 'crew_name', 'crew_profile_path'],
      dtype='object')

In [66]:
crew_df['crew_name'].unique()

array(['John Lasseter', 'Joss Whedon', 'Andrew Stanton', ...,
       'Dante Perez', 'Jeffrey Goldenberg', 'Daisy Asquith'], dtype=object)

In [6]:
# Armo el data que usare para la funcion:


datasets_df_nuevo = datasets_df.rename(columns={
    'title': 'title',
    'release_date': 'release_date',
    'budget': 'budget',
    'revenue':'revenue'
})

df_directores = crew_df.merge(datasets_df, on='id', how='left')

In [7]:
df_directores

,id,crew_credit_id,crew_department,crew_gender,crew_id,crew_job,crew_name,crew_profile_path,original_language,overview,...,name_genres,id_genres,name_companies,id_companies,Cod_countries,country_name,budget,revenue,release_year,return
0,862,52fe4284c3a36847f8024f49,Directing,2,7879.0,Director,John Lasseter,/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg,en,"Led by Woody, Andy's toys live happily in his ...",...,Animation,16.0,Pixar Animation Studios,3.0,US,United States of America,30000000.0,373554033.0,1995.0,12.451801
1,862,52fe4284c3a36847f8024f4f,Writing,2,12891.0,Screenplay,Joss Whedon,/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg,en,"Led by Woody, Andy's toys live happily in his ...",...,Animation,16.0,Pixar Animation Studios,3.0,US,United States of America,30000000.0,373554033.0,1995.0,12.451801
2,862,52fe4284c3a36847f8024f55,Writing,2,7.0,Screenplay,Andrew Stanton,/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg,en,"Led by Woody, Andy's toys live happily in his ...",...,Animation,16.0,Pixar Animation Studios,3.0,US,United States of America,30000000.0,373554033.0,1995.0,12.451801
3,862,52fe4284c3a36847f8024f5b,Writing,2,12892.0,Screenplay,Joel Cohen,/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg,en,"Led by Woody, Andy's toys live happily in his ...",...,Animation,16.0,Pixar Animation Studios,3.0,US,United States of America,30000000.0,373554033.0,1995.0,12.451801
4,862,52fe4284c3a36847f8024f61,Writing,0,12893.0,Screenplay,Alec Sokolow,/v79vlRYi94BZUQnkkyznbGUZLjT.jpg,en,"Led by Woody, Andy's toys live happily in his ...",...,Animation,16.0,Pixar Animation Studios,3.0,US,United States of America,30000000.0,373554033.0,1995.0,12.451801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
632131,67758,52fe4776c3a368484e0c8399,Sound,0,549356.0,Original Music Composer,Richard McHugh,NaN,en,"When one of her hits goes wrong, a professiona...",...,Comedy,35.0,Foxboro Entertainment,85122.0,US,United States of America,0.0,0.0,2003.0,0.000000
632132,67758,52fe4776c3a368484e0c839f,Camera,2,58818.0,Director of Photography,João Fernandes,NaN,en,"When one of her hits goes wrong, a professiona...",...,Comedy,35.0,Foxboro Entertainment,85122.0,US,United States of America,0.0,0.0,2003.0,0.000000
632133,227506,533bccebc3a36844cf0011a7,Directing,0,1085341.0,Director,Yakov Protazanov,/yyjbGdCs2ZN6IlZNCfmBWyuRDlt.jpg,en,"In a small town live two brothers, one a minis...",...,Drama,18.0,NaN,NaN,RU,Russia,0.0,0.0,1917.0,0.000000
632134,227506,58ebbc26925141281908aa0a,Production,2,1195656.0,Producer,Joseph N. Ermolieff,NaN,en,"In a small town live two brothers, one a minis...",...,Drama,18.0,NaN,NaN,RU,Russia,0.0,0.0,1917.0,0.000000
632135,461257,593e676c92514105b702e68e,Directing,0,1344495.0,Director,Daisy Asquith,NaN,en,50 years after decriminalisation of homosexual...,...,Romance,10749.0,Aegis Film Fund,7309.0,GB,United Kingdom,0.0,0.0,2017.0,0.000000

In [8]:
df_directores['crew_department'].unique().tolist()

['Directing',
 'Writing',
 'Production',
 'Editing',
 'Art',
 'Sound',
 'Visual Effects',
 'Crew',
 'Lighting',
 'Camera',
 'Costume & Make-Up',
 nan,
 'Actors']

In [9]:
# Filtrar las filas en las que la columna 'crew_department' es igual a 'Directing'
df_directores = df_directores[df_directores['crew_department'] == 'Directing']

In [10]:
df_directores.head()

,id,crew_credit_id,crew_department,crew_gender,crew_id,crew_job,crew_name,crew_profile_path,original_language,overview,...,name_genres,id_genres,name_companies,id_companies,Cod_countries,country_name,budget,revenue,release_year,return
0,862,52fe4284c3a36847f8024f49,Directing,2,7879.0,Director,John Lasseter,/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg,en,"Led by Woody, Andy's toys live happily in his ...",...,Animation,16.0,Pixar Animation Studios,3.0,US,United States of America,30000000.0,373554033.0,1995.0,12.451801
25,862,589213d39251412dc8009832,Directing,0,1748707.0,Layout,Roman Figun,NaN,en,"Led by Woody, Andy's toys live happily in his ...",...,Animation,16.0,Pixar Animation Studios,3.0,US,United States of America,30000000.0,373554033.0,1995.0,12.451801
82,862,589213e2c3a3680973009026,Directing,0,1748709.0,Layout,Desirée Mourad,NaN,en,"Led by Woody, Andy's toys live happily in his ...",...,Animation,16.0,Pixar Animation Studios,3.0,US,United States of America,30000000.0,373554033.0,1995.0,12.451801
109,8844,52fe44bfc3a36847f80a7c7d,Directing,2,4945.0,Director,Joe Johnston,/fok4jaO62v5IP6hkpaaAcXuw2H.jpg,en,When siblings Judy and Peter discover an encha...,...,Comedy,35.0,TriStar Pictures,559.0,US,United States of America,65000000.0,262797249.0,1995.0,4.043035
122,15602,52fe466a9251416c75077a89,Directing,2,26502.0,Director,Howard Deutch,/68Vae1HkU1NxQZ6KEmuxIpno7c9.jpg,en,A family wedding reignites the ancient feud be...,...,Family,10751.0,Teitler Film,2550.0,US,United States of America,0.0,0.0,1995.0,0.000000

In [11]:
# Filtrar las filas en las que la columna 'crew_department' es igual a 'Directing'
df_directores = df_directores[df_directores['crew_job'] == 'Director']

In [12]:
df_directores.head()

,id,crew_credit_id,crew_department,crew_gender,crew_id,crew_job,crew_name,crew_profile_path,original_language,overview,...,name_genres,id_genres,name_companies,id_companies,Cod_countries,country_name,budget,revenue,release_year,return
0,862,52fe4284c3a36847f8024f49,Directing,2,7879.0,Director,John Lasseter,/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg,en,"Led by Woody, Andy's toys live happily in his ...",...,Animation,16.0,Pixar Animation Studios,3.0,US,United States of America,30000000.0,373554033.0,1995.0,12.451801
109,8844,52fe44bfc3a36847f80a7c7d,Directing,2,4945.0,Director,Joe Johnston,/fok4jaO62v5IP6hkpaaAcXuw2H.jpg,en,When siblings Judy and Peter discover an encha...,...,Comedy,35.0,TriStar Pictures,559.0,US,United States of America,65000000.0,262797249.0,1995.0,4.043035
122,15602,52fe466a9251416c75077a89,Directing,2,26502.0,Director,Howard Deutch,/68Vae1HkU1NxQZ6KEmuxIpno7c9.jpg,en,A family wedding reignites the ancient feud be...,...,Family,10751.0,Teitler Film,2550.0,US,United States of America,0.0,0.0,1995.0,0.000000
126,31357,52fe44779251416c91011acb,Directing,2,2178.0,Director,Forest Whitaker,/4pMQkelS5lK661m9Kz3oIxLYiyS.jpg,en,"Cheated on, mistreated and stepped on, the wom...",...,Adventure,12.0,Interscope Communications,10201.0,US,United States of America,16000000.0,81452156.0,1995.0,5.090760
141,11862,52fe44959251416c75039eef,Directing,2,56106.0,Director,Charles Shyer,/hnWGd74CbmTcDCFQiJ8SYLazIXW.jpg,en,Just when George Banks has recovered from his ...,...,Fantasy,14.0,Warner Bros.,6194.0,US,United States of America,0.0,76578911.0,1995.0,0.000000

In [ ]:
# AHORA QUE ESTA FILTADO POR DEPARTAMENTO DIRECTING Y UNICAMENTE POR DIRECTOR YA PUEDO ELIMINAR LAS COLUMNAS DEJANDO SOLAMENTE LO NOMBRES.


df_directores = datasets_df.rename(columns={
    'id':'id',
    'title': 'title',
    'release_date': 'release_date',
    'budget': 'budget',
    'revenue':'revenue',
    'crew_department':'crew_department',
    'crew_job':'crew_job',
    'crew_name':'crew_name'
})

In [31]:
# Ahora voy a reestructurar con las columnas que necesito:

df_directores = df_directores.rename(columns={
    'id': 'id',
    'title': 'title',
    'release_date': 'release_date',
    'budget': 'budget',
    'revenue': 'revenue',
    'crew_name': 'Nombre Director'
})

In [32]:
df_directores_final = pd.DataFrame(df_directores, columns=[
    'id',
   'title',
   'release_date',
   'budget',
    'revenue','return',
   'Nombre Director'])

In [33]:
df_directores_final.head(10)

,id,title,release_date,budget,revenue,return,Nombre Director
0,862,Toy Story,1995-10-30,30000000.0,373554033.0,12.451801,John Lasseter
109,8844,Jumanji,1995-12-15,65000000.0,262797249.0,4.043035,Joe Johnston
122,15602,Grumpier Old Men,1995-12-22,0.0,0.0,0.000000,Howard Deutch
126,31357,Waiting to Exhale,1995-12-22,16000000.0,81452156.0,5.090760,Forest Whitaker
141,11862,Father of the Bride Part II,1995-02-10,0.0,76578911.0,0.000000,Charles Shyer
143,949,Heat,1995-12-15,60000000.0,187436818.0,3.123947,Michael Mann
214,11860,Sabrina,1995-12-15,58000000.0,0.0,0.000000,Sydney Pollack
215,11860,Sabrina,1995-12-15,58000000.0,0.0,0.000000,Sydney Pollack
322,45325,Tom and Huck,1995-12-22,0.0,0.0,0.000000,Peter Hewitt
324,9091,Sudden Death,1995-12-22,35000000.0,64350171.0,1.838576,Peter Hyams

In [35]:
# vi que tengo duplicadas asi que modificare el data
df_directores_final = df_directores_final.drop_duplicates(subset=['title'], keep='first')

In [36]:
df_directores_final.head(10)

,id,title,release_date,budget,revenue,return,Nombre Director
0,862,Toy Story,1995-10-30,30000000.0,373554033.0,12.451801,John Lasseter
109,8844,Jumanji,1995-12-15,65000000.0,262797249.0,4.043035,Joe Johnston
122,15602,Grumpier Old Men,1995-12-22,0.0,0.0,0.000000,Howard Deutch
126,31357,Waiting to Exhale,1995-12-22,16000000.0,81452156.0,5.090760,Forest Whitaker
141,11862,Father of the Bride Part II,1995-02-10,0.0,76578911.0,0.000000,Charles Shyer
143,949,Heat,1995-12-15,60000000.0,187436818.0,3.123947,Michael Mann
214,11860,Sabrina,1995-12-15,58000000.0,0.0,0.000000,Sydney Pollack
322,45325,Tom and Huck,1995-12-22,0.0,0.0,0.000000,Peter Hewitt
324,9091,Sudden Death,1995-12-22,35000000.0,64350171.0,1.838576,Peter Hyams
333,710,GoldenEye,1995-11-16,58000000.0,352194034.0,6.072311,Martin Campbell

In [37]:
# Guardar el DataFrame en un archivo CSV
directores = 'df_directores_Def.csv'
df_directores_final.to_csv(directores, index=False)

print(f"El DataFrame ha sido guardado en el archivo '{directores}'")

El DataFrame ha sido guardado en el archivo 'df_directores_Def.csv'

In [61]:
def get_director(nombre_director):
    #  DataFrame para obtener las filas correspondientes al director consultado
    peliculas_director = df_directores_final[df_directores_final['Nombre Director'] == nombre_director]

    # Calcular el éxito del director medido a través del retorno (ganancia total / costo total)
    costo_total = peliculas_director['budget'].sum()
    ganancia_total = peliculas_director['revenue'].sum()
    retorno_director = ganancia_total / costo_total if costo_total != 0 else 0

    # Crear una lista para almacenar la información de cada película
    peliculas_info = []

    # Recorrer las filas del DataFrame y obtener la información de cada película
    for _, pelicula in peliculas_director.iterrows():
        info_pelicula = {
            'nombre_pelicula': pelicula['title'],
            'fecha_lanzamiento': pelicula['release_date'],
            'retorno_individual': pelicula['return'],
            'costo': pelicula['budget'],
            'ganancia': pelicula['revenue']
        }
        peliculas_info.append(info_pelicula)

    # Crear un diccionario con la información del director y las películas
    resultado = [
         nombre_director,
       retorno_director,
         peliculas_info
    ]

    return resultado

*  nombre_director (el nombre del director que se desea consultar) 
* df_directores_final (DataFrame películas y directores).

* peliculas_director = df_directores_final[df_directores_final['Nombre Director'] == nombre_director] 
lo que hace es filtrar el DataFrame df_directores_final para obtener las filas correspondientes al director cuyo nombre coincide con el valor de nombre_director. Es decir, selecciona las películas que fueron dirigidas por el director que estamos buscando.

* peliculas_director['budget'].sum(): Esta línea calcula el costo total de todas las películas dirigidas por el director. 
este suma los valores de la columna 'budget' (presupuesto) de las filas filtradas en peliculas_director.

* ganancia_total = peliculas_director['revenue'].sum(): calculo de  la ganancia total de todas las películas dirigidas por el director. 
Suma los valores de la columna 'revenue' (ganancia) de las filas filtradas en peliculas_director.

In [65]:
# Directores

df_directores_final['Nombre Director'].unique()

array(['John Lasseter', 'Joe Johnston', 'Howard Deutch', ...,
       'Beth David', 'Aaron Osborne', 'Daisy Asquith'], dtype=object)

In [62]:
# EJEMPLO DE USO DE LA DEF

nombre_director = 'Martin Scorsese'
resultado = get_director(nombre_director)
resultado

['Martin Scorsese',
 2.286246108683528,
 [{'nombre_pelicula': 'Casino',
   'fecha_lanzamiento': '1995-11-22',
   'retorno_individual': 2.2329302884615383,
   'costo': 52000000.0,
   'ganancia': 116112375.0},
  {'nombre_pelicula': 'Taxi Driver',
   'fecha_lanzamiento': '1976-02-07',
   'retorno_individual': 21.74044153846154,
   'costo': 1300000.0,
   'ganancia': 28262574.0},
  {'nombre_pelicula': 'The Age of Innocence',
   'fecha_lanzamiento': '1993-09-17',
   'retorno_individual': 0.948689411764706,
   'costo': 34000000.0,
   'ganancia': 32255440.0},
  {'nombre_pelicula': 'GoodFellas',
   'fecha_lanzamiento': '1990-09-12',
   'retorno_individual': 1.87345576,
   'costo': 25000000.0,
   'ganancia': 46836394.0},
  {'nombre_pelicula': 'Raging Bull',
   'fecha_lanzamiento': '1980-11-14',
   'retorno_individual': 1.2777777777777777,
   'costo': 18000000.0,
   'ganancia': 23000000.0},
  {'nombre_pelicula': 'Cape Fear',
   'fecha_lanzamiento': '1991-11-15',
   'retorno_individual': 5.208571428571428,
   'costo': 35000000.0,
   'ganancia': 182300000.0},
  {'nombre_pelicula': 'Kundun',
   'fecha_lanzamiento': '1997-12-25',
   'retorno_individual': 0.2030281785714285,
   'costo': 28000000.0,
   'ganancia': 5684789.0},
  {'nombre_pelicula': 'The Last Temptation of Christ',
   'fecha_lanzamiento': '1988-08-12',
   'retorno_individual': 1.1962264285714286,
   'costo': 7000000.0,
   'ganancia': 8373585.0},
  {'nombre_pelicula': 'The Color of Money',
   'fecha_lanzamiento': '1986-10-07',
   'retorno_individual': 3.7894189855072464,
   'costo': 13800000.0,
   'ganancia': 52293982.0},
  {'nombre_pelicula': 'Bringing Out the Dead',
   'fecha_lanzamiento': '1999-10-22',
   'retorno_individual': 0.0,
   'costo': 32000000.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'Boxcar Bertha',
   'fecha_lanzamiento': '1972-06-14',
   'retorno_individual': 0.0,
   'costo': 600000.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'The Last Waltz',
   'fecha_lanzamiento': '1978-05-01',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 321952.0},
  {'nombre_pelicula': 'Gangs of New York',
   'fecha_lanzamiento': '2002-12-14',
   'retorno_individual': 1.93772504,
   'costo': 100000000.0,
   'ganancia': 193772504.0},
  {'nombre_pelicula': 'The King of Comedy',
   'fecha_lanzamiento': '1982-12-18',
   'retorno_individual': 0.0,
   'costo': 20000000.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'After Hours',
   'fecha_lanzamiento': '1985-09-13',
   'retorno_individual': 2.357626888888889,
   'costo': 4500000.0,
   'ganancia': 10609321.0},
  {'nombre_pelicula': 'Mean Streets',
   'fecha_lanzamiento': '1973-10-02',
   'retorno_individual': 6.0,
   'costo': 500000.0,
   'ganancia': 3000000.0},
  {'nombre_pelicula': 'My Voyage to Italy',
   'fecha_lanzamiento': '1999-09-11',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': "Alice Doesn't Live Here Anymore",
   'fecha_lanzamiento': '1974-12-09',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': "Who's That Knocking at My Door",
   'fecha_lanzamiento': '1967-11-15',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'New York, New York',
   'fecha_lanzamiento': '1977-06-21',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'No Direction Home: Bob Dylan',
   'fecha_lanzamiento': '2005-07-21',
   'retorno_individual': 0.0,
   'costo': 2000000.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'A Personal Journey with Martin Scorsese Through American Movies',
   'fecha_lanzamiento': '1995-05-21',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'The Departed',
   'fecha_lanzamiento': '2006-10-05',
   'retorno_individual': 3.2205261555555555,
   'costo': 90000000.0,
   'ganancia': 289847354.0},
  {'nombre_pelicula': 'Shine a Light',
   'fecha_lanzamiento': '2008-02-07',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'Shutter Island',
   'fecha_lanzamiento': '2010-02-18',
   'retorno_individual': 3.6850524375,
   'costo': 80000000.0,
   'ganancia': 294804195.0},
  {'nombre_pelicula': 'Italianamerican',
   'fecha_lanzamiento': '1974-01-01',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'Public Speaking',
   'fecha_lanzamiento': '2010-11-22',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'A Letter to Elia',
   'fecha_lanzamiento': '2010-09-04',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'American Boy: A Profile of: Steven Prince',
   'fecha_lanzamiento': '1978-09-16',
   'retorno_individual': 0.0,
   'costo': 155000.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'Street Scenes',
   'fecha_lanzamiento': '1970-09-14',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'George Harrison: Living in the Material World',
   'fecha_lanzamiento': '2011-10-05',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'Hugo',
   'fecha_lanzamiento': '2011-11-22',
   'retorno_individual': 1.0927656470588236,
   'costo': 170000000.0,
   'ganancia': 185770160.0},
  {'nombre_pelicula': 'The Wolf of Wall Street',
   'fecha_lanzamiento': '2013-12-25',
   'retorno_individual': 3.92000694,
   'costo': 100000000.0,
   'ganancia': 392000694.0},
  {'nombre_pelicula': 'The Big Shave',
   'fecha_lanzamiento': '1968-01-01',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': "What's a Nice Girl Like You Doing in a Place Like This?",
   'fecha_lanzamiento': '1963-01-01',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'The 50 Year Argument',
   'fecha_lanzamiento': '2014-06-29',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'The Key to Reserva (La clave Reserva)',
   'fecha_lanzamiento': '2007-12-14',
   'retorno_individual': 0.0,
   'costo': 0.0,
   'ganancia': 0.0},
  {'nombre_pelicula': 'Bad',
   'fecha_lanzamiento': '1987-08-31',
   'retorno_individual': 0.0,
   'costo': 2000000.0,
   'ganancia': 0.0}]]